#pragma once
#include "juce_graphics/juce_graphics.h"

namespace melatonin::blur
{
    // According to CSS spec, the std dev is 1/2 the radius
    // https://www.w3.org/TR/css-backgrounds-3/#shadow-blur
    //  "...the resulting shadow must approximate (with each pixel being within 5% of its expected value)
    //  the image that would be generated by applying to the shadow a Gaussian blur
    //  with a standard deviation equal to half the blur radius."
    //
    // According to math, it's more like this:
    // stdDev = radius / sqrt(2)
    //
    // But according to actual CSS and Figma output (to pass our tests) it needs to even smaller:
    constexpr float radiusToStdDev = 1.0f / 1.25f;
    inline void direct2DSingleChannel (juce::Image& img, size_t radius);
    inline void direct2DARGB (juce::Image& srcImage, juce::Image& dstImage, size_t radius);
}
